<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="copyright-cont">
<small class="copyright">
    <span><?= /* @escapeNotVerified */ $block->getCopyright() ?></span>
    <img class="copyright_payment" src="<?php echo $block->getViewFileUrl('images/footer_payment.png'); ?>" alt="<?= /* @escapeNotVerified */ __('payment methods') ?>">
</small>
</div>

        	